issue 3.2
RomanRudakov/liquid-log pull request #3
Opened 2017-10-30 20:38 UTC by RomanRudakov

Решил создать отдельный класс и сразу забить в него данные application.properties, а потом по мере надобности брать их из него. Теперь дополнительные аргументы не нужны.
@ykalemi

2017-10-31 07:17 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/App.java
> +            storage = new InfluxDAO(InfluxControl.HOST, InfluxControl.USER, InfluxControl.PASSWORD);
Ок, попытка хорошая (в смысле, работать будет), но это с архитектурной точки зрения не очень хорошо - получать свойства из файла конфигурации и складывать их в публичные статичные переменные.

На самом деле, есть намного более простой способ. Этот класс - App - сам должен быть спринг-бином, здесь не должно быть статичного метода DoParser.

Если этот класс будет являться бином, то он сможет делать `@Autowire` для объекта InfluxDAO (см. как это делается при отображении). И тогда не нужно будет здесь создавать новый экземпляр класса InfluxDAO (что, в общем, не очень правильно, потому что это по своей сути синглтон).

2017-11-17 16:31 UTC, RomanRudakov commented
У меня не получается разобраться как сделать App бином, поэтому пока отложил это на потом
Добавил интерфейсы, но не организовал пока поддержки этих интерфейсов классом TopParser. Правильно ли пока двигаюсь по решению задачи или нет? Прошу проверить
@ykalemi

2017-11-17 16:38 UTC, ykalemi requested changes
А по поводу spring bean - вы были на последней лекции?

2017-11-17 16:38 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/GCParser.java
> +    {
одной из задач было - избавиться от дублирования. Сейчас у вас в обоих парсерах два одинаковых цикла (+ еще похожий в TopParser). А если понадобиться добавить новые парсеры - то этот код будет копироваться в каждый из них.

лучше вернуть цикл в App, но чтобы он там был один-единственный. А парсеры бы вызывались только на одну строку. Могу сразу подсказать, чтобы дело быстрее пошло - пусть DataParser принимает в методе parseData два аргумента - строка и DataSet

2017-11-17 20:29 UTC, RomanRudakov commented on src/main/java/ru/naumen/sd40/log/parser/GCParser.java
> +    {
я правильно понимаю, что TopParser во время парсинга создает ключ из времени, а потом кидает в Map данные до тех пор, пока не встретит опять стоку со временем?

2017-11-18 04:13 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/GCParser.java
> +    {
Да, правильно. Потому что - так устроен файл Top. Сначала идет строка со временем, потом несколько строк с данными, которые относятся к этому времени. Пример есть в телеграмме. Собственно, надо такую логику сделать для TopTimeParser, а сам TopParser при этом сильно упростится

2017-11-18 19:45 UTC, RomanRudakov commented
Избавился от дублирования кода и оставил основной код в App. Вроде работает. Прошу проверить
@ykalemi

2017-11-19 04:47 UTC, ykalemi requested changes
Да, уже почти хорошо. Единственно, кажется ErrorsParser сейчас вообще выпал из приложения?

и пара стилистических замечания

2017-11-19 04:47 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/TopTimeParser.java
> +	private long TIME = 0L;
принято заглавными буквами писать константы, TIME - это не константа

2017-11-19 04:47 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/TimeParserInterface.java
> +public interface TimeParserInterface {
принято названия устраивать таким образом:
TimeParser - для интерфейса, TimeParserImpl - для реализации (если вы не хотите назвать реализацию как-то более конкретно)

2017-11-19 07:44 UTC, ykalemi approved these changes
норм!

2017-11-19 08:00 UTC, merged