issue 5
RomanRudakov/liquid-log pull request #4
Opened 2017-11-25 12:44 UTC by RomanRudakov

Теперь данные сохраняются при парсинге. Выделил интерфейс InflaxDAO, но тестов пока нет. Прошу проверить @ykalemi

2017-11-25 16:52 UTC, ykalemi requested changes
выглядит хорошо. Жду тесты

2017-11-25 16:52 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/SaveDataParser.java
> +		influxDb = nameDb.replaceAll("-", "_");
Переменная influxDb используется только один раз. Нужно ли ее сохранять в поле объекта?

2017-11-26 10:00 UTC, RomanRudakov commented on src/main/java/ru/naumen/sd40/log/parser/SaveDataParser.java
> +		influxDb = nameDb.replaceAll("-", "_");
просто эта переменная используется еще в методе get

2017-11-26 13:43 UTC, RomanRudakov commented
Добавил тесты

2017-11-26 16:59 UTC, RomanRudakov commented
Добавил тесты. Прошу проверить @ykalemi

2017-11-27 07:19 UTC, ykalemi approved these changes

2017-11-27 07:19 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/SaveDataParser.java
> +		influxDb = nameDb.replaceAll("-", "_");
ok

2017-11-27 08:51 UTC, merged