issue 6
RomanRudakov/liquid-log pull request #5
Opened 2017-12-03 12:21 UTC by RomanRudakov

Созданы отдельные классы под данные и теперь парсеры и данные разделены. Прошу проверить @ykalemi

2017-12-03 19:29 UTC, ykalemi requested changes
Направление верное. Но я хочу, чтобы вы сделали еще один пункт из задания:
> В интерфейсе DataParser должен использоваться интерфейс DataSet. А в конкретной реализации DataParser (например, TopParser) - конкретный DataSet (например, TopDataSet)

Суть в том, что DataSet должен стать интерфейсом, а каждый из классов - его реализации. Не должно быть больше такого DataSet, который хранит в себе все возможные данные от всех возможных парсеров

2017-12-03 19:37 UTC, ykalemi commented
А, подождите, это из следующего задания. Вы сдаете сейчас задание "Каждый DataParser -> Spring Bean" ? Тогда не хватает именно этой части, чтобы каждый парсер стал spring bean-ом

2017-12-03 20:16 UTC, RomanRudakov commented
Сделал парсеры бинами. Вроде все работает как надо. Прошу проверить @ykalemi

2017-12-04 15:04 UTC, ykalemi approved these changes

2017-12-05 17:59 UTC, merged