issue 7
RomanRudakov/liquid-log pull request #6
Opened 2017-12-09 17:33 UTC by RomanRudakov

Теперь DataSet интерфейс, каждый вид данных сохраняется отдельно. Прошу проверить @ykalemi

2017-12-09 18:40 UTC, ykalemi requested changes
хорошо, но есть небольшой момент

2017-12-09 18:40 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/Parser.java
> +        		dataParser = new SdngParser();
а почему sdngparser не сделать бином?
и errorParser и actionDone внедряются в этот класс, но никак не используются.

2017-12-10 09:34 UTC, RomanRudakov commented
Исправил ошибки. Прошу проверить @ykalemi

2017-12-11 09:30 UTC, ykalemi approved these changes

2017-12-11 10:54 UTC, merged